# Generated by Django 4.2.10 on 2024-02-10 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TERMINAL_ID', models.CharField(max_length=100)),
                ('CARD_NUMBER', models.CharField(max_length=16)),
                ('FROM_ACCOUNT_NO', models.CharField(max_length=20)),
                ('REQUESTED_AMOUNT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BUSINESS_DATE', models.DateField()),
                ('TRXN_TIME', models.TimeField()),
                ('STATUS', models.CharField(max_length=100)),
                ('bank', models.CharField(choices=[('CBE', 'CBE'), ('Other', 'Other')], default='CBE', max_length=5)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
