# Generated by Django 4.2.10 on 2024-02-10 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reconiliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='bank',
            field=models.CharField(choices=[('CBE', 'CBE'), ('OTHER', 'OTHER')], default='CBE', max_length=5),
        ),
        migrations.CreateModel(
            name='ActivtyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATM_BR_NUMBER', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=16)),
                ('DR_ACCT', models.CharField(max_length=20)),
                ('TXN_AMOUNT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TXN_DATE', models.DateField()),
                ('TXN_TIME', models.TimeField()),
                ('bank', models.CharField(choices=[('CBE', 'CBE'), ('OTHER', 'OTHER')], default='CBE', max_length=5)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
